### ISSUE TITLE
Revision checklist

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/eicu-data-paper#2]
In order to process your revised manuscript, we will require the following items: 

* [x] A cover letter describing your response to our editorial requests. 
* [x] A point-by-point response to any issues raised by our referees. 
* [x] The revised version of your text as a Word or TeX/LaTeX file. 
* [x] The final versions of any Supplementary Information files. 
* [x] Publication quality figures in the TIFF, EPS, or PDF formats. 
* [x] Final accession numbers or DOIs for any deposited datasets.
